version: '2'
services: 
  web:
    image: node:7.2
    ports: 
      - "8000:8000"
    volumes: 
      - ./:/app
    environment:
      PORT: '8000'
      MONGO_URI: 'mongodb://mongodb:27017/node-mongodb-app'
    depends_on:
      - mongodb
    entrypoint: 'node /app/example'
  mongodb:
    image: mongo:3.2
    volumes: 
      - /data/db
    hostname: mongodb
    ports:
      - "27017:27017"